# Generated by Django 3.0.8 on 2020-08-08 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ram', models.CharField(choices=[('1 Gb', '1 Gb'), ('2 Gb', '2 Gb'), ('4 Gb', '4 Gb'), ('8 Gb', '8 Gb'), ('16 Gb', '16 Gb')], max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptops.Company')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptops.Cpu')),
            ],
        ),
    ]
